# HCFactions by drtshock and milkywayz 
# Report issues https://github.com/drtshock/HCFProblems/issues/new
# Live support http://webchat.esper.net/?channels=drtshock&prompt=1

# Made with love <3

# Debug
# Turn this on if you are having issues with something and working on resolving them.
# This will spam your console with information that is useful if you know how to read the source.
# It's suggested that you only turn this on at the direction of a developer.
debug: false

# Prevent find factions exploit
# This will help limit how many times a player can be sent a map of factions.
# Set this to the cooldown you want, in miliseconds, for a map to be shown to a player.
# If you want to log when a player violates this (only happens on chunk enter so it shouldn't be too spammy),
#   set log to true and it will be logged to console as "player tried to show a faction map too soon and triggered exploit blocker."
findfactionsexploit:
  cooldown: 2000 # in miliseconds. 2000 = 2 seconds.
  log: false

# Default Relation allows you to change the default relation for Factions.
# Example usage would be so people can't leave then make a new Faction while Raiding
#   in order to be able to execute commands if the default relation is neutral.
# This has always been neutral.
default-relation: "enemy"

# Portal Creation
# Do you want to limit portal creation?
portals:
  limit: false # will disable the below check if set to false

  # What should the minimum relation be to create a portal in territory?
  # Goes in the order of: ENEMY, NEUTRAL, ALLY, MEMBER.
  # Minimum relation allows that and all listed to the right to create portals.
  # Example: put ALLY to allow ALLY and MEMBER to be able to create portals.
  minimum-relation: MEMBER # If typed incorrectly, defaults to NEUTRAL.

# Warps
# What should be the max amount of warps that a Factoin can set?
max-warps: 5

# This is the cost section for warps.
# It will charge them each time the command would be successful. (won't charge on erroneous /f warp attempts).
# You can use decimal places here.
# If enabled is set to false, it will ignore the values.
warp-cost:
  enabled: false
  setwarp: 5.0
  delwarp: 5.0
  warp: 5.0

# Pistons
# Should we disable pistons in Faction territory? This will prevent people from doing something like:
# http://i.gyazo.com/6a1a31222e58a5d60ff341c13f6a8404.gif
disable-pistons-in-territory: false

# ToolTips in /f show
tooltips:

  # Faction show
  # This shows up when someone hovers over a faction name in /f show
  # You can use color codes and any variable here
  list:
    - "&6Leader: &r{leader}"
    - "&6Claimed: &d{land} &6/ &d{max-land}"
    - "&6Raidable: {raidable}"
    - "&6DTR: &d{dtr} &6/ &d{max-dtr}"
    - "&6Members: &d{online-count} &6/ &d{faction-size}"

  # Player show
  # This shows up when someone hovers over a player name in /f show
  # You can use any player variable
  show:
    - "&6Last Seen: &f{last-seen}"
    - "&6Rank: &f{group}"
    - "&6Balance: &a${player-balance}"

############################################################
# +------------------------------------------------------+ #
# |                  Scoreboard settings                 | #
# +------------------------------------------------------+ #
############################################################

scoreboard:
  expiration: 7 # in seconds, how long should an info scoreboard persist?

# FInfo scoreboard is displayed when a player walks into a new Faction's territory.
# Scoreboard disappears after <expiration> seconds.
# You can use any variable and color codes here
  finfo-enabled: false
  finfo:
    - "&3Members"
    - "{online-count}/{faction-size}"
    - "&4DTR"
    - "{dtr}/{max-dtr}&r"
    - "&9Raidable: {raidable}"
    - "&bLand"
    - "{land}/{max-land}&f"

# Default board that will always show up if a player wants it to.
# This can show any arbitrary text or you can use any of the variables as well.
  default-enabled: true
  default-title: "{name}" # Can use any of the values from above but this won't update once it's set (so don't set {balance}).
  default-update-interval: 5 # in seconds.

  # This will show faction prefixes colored based on relation on nametags and in the tab.
  #   The scoreboard needs to be enabled for this to work.
  default-prefixes: true

  default:
    - "&6Your Faction"
    - "{faction}"
    - "&4Faction DTR"
    - "{dtr}/{max-dtr}&r"
    - "&aLand"
    - "{land}/{max-land}&f"

  # Should we also send the chat message when a player enters a new claim?
  # By default, if we have a scoreboard enabled, no message will be sent
  # This value only applies when either a default or info scoreboard is enabled
  # Remember, you can configure the message in lang.yml
  also-send-chat: false

# Warpup settings
warmups:
  # Delay for /f home , 0 for none
  f-home: 0
  # Delay for /f warp, 0 for none
  f-warp: 0

# Max Relation Types
# Limits factions to having a max number of each relation.
# Setting to 0 means none allowed. -1 for disabled.
# This will have no effect on default or existing relations, only when relations are changed.
# It is advised that you set the default relation to -1 so they can always go back to that.
# Otherwise Factions could be stuck with not being able to unenemy other Factions.
max-relations:
  enabled: true
  ally: 2
  truce: 10
  neutral: -1
  enemy: 10

# WorldBorder support 
# A buffer of 0 means faction claims can go right up to the border of the world.
# The buffer is in chunks, so 1 as a buffer means an entire chunk of buffer between 
# the border of the world and what can be claimed to factions
world-border:
  buffer: 0

############################################################
# +------------------------------------------------------+ #
# |                    HCF Settings                      | #
# +------------------------------------------------------+ #
############################################################

hcf:
  # DTR (death till raidable) will be in /f show if enabled.
  # When DTR is below 0, the faction is considered raidable
  dtr:
    # Maximum DTR a faction can have 
    max-faction-dtr: 5.5
    # How much DTR should we charge a faction for kicking a player when they are frozen
    # Set to 0 to disable penalty, but remember a faction can kick low dtr players to remain unraidable if theres no penalty!
    kick-penalty: 1.0
    # How many seconds after a player exits combat may they leave or be kicked
    leave-cooldown: 0
    # Minimum DTR a faction can have 
    min-faction-dtr: -6.0
    # How much DTR is lost on death
    death-dtr: 1.0
    # How much DTR is replenished per faction member per minute 
    minute-dtr: 0.01
    # How much max DTR should a faction gain per player?
    # Max DTR = min(player-dtr * faction size, max-faction-dtr)
    player-dtr: .51
    # How much DTR should a solo faction get?
    # Used so solo factions can have more than 1 death before raidable.
    solo-faction: 1.01
    # After a player dies, how long should the faction not be able to regen dtr?
    # This resets on each death but does not accumulate.
    # Set to 0 for no freeze. Time is in seconds.
    dtr-freeze: 0
    # DTR Freeze background regeneration
    # False unless you want factions to gain back the DTR
    # they would have generated during their DTR freeze
    allow-background-regen: false
    # Should we let players leave a frozen faction?
    freeze-leave: false
    # Should we let players join a frozen faction?
    freeze-join: true
    # Should we let frozen factions disband?
    freeze-disband: false
  fstuck:
    # Time in seconds before teleport occurs
    delay: 60
    # Number of blocks player can move before teleport cancels
    # Note: This is used to check distance right before teleport, it doesnt cancel as soon as you leave the radius
    radius: 10
    # list of block ids you want to rule out from f stuck
    # we check the block under, at, and two above (player head and then space above) for this block
    # if it exists in any of the 4 locations, we will skip and find a safer teleport location
    # NOTE: THIS IS ONLY USED IF ESSENTIALS IS NOT AVAILABLE FOR SAFE TELEPORT!
    black-list:
    - 8
    - 9
    - 10
    - 11
    - 51

  # Max land a faction can have claimed
  faction-land-max: 36
  
  # How much land a faction gets per member
  land-per-player: 6

  # Allows PVP betweeen members and allys of one faction
  friendly-fire: false

  # Buffer Zone
  # Buffer Zone is an chunk area required between claims of different Factions.
  # This is default to 0 and has always been that way. Meaning Factions can have
  #   claims that border each other.
  # If this is set to 3, then Factions need to have 3 chunks between their claim
  #   and another Faction's claim.
  # It's recommended to keep this pretty low as the radius check could be a
  #   heavy operation if set to a large number.
  # If this is set to 0, we won't even bother checking which is how Factions has
  #   always been.
  buffer-zone: 0

# Enable to use the old help system
use-old-help: false

############################################################
# +------------------------------------------------------+ #
# |                Configurable /f help                  | #
# +------------------------------------------------------+ #
############################################################

help:
  # You can change the page name to whatever you like
  # We use '1' to preserve default functionality of /f help 1
  '1':
    - '&e&m----------------------------------------------'
    - '                      &c&lHCF Help               '
    - '&e&m----------------------------------------------'
    - '&3/f create  &e>>  &7Create your own faction'
    - '&3/f who      &e>>  &7Show factions info'
    - '&3/f tag      &e>>  &7Change faction tag'
    - '&3/f join     &e>>  &7Join faction'
    - '&3/f list      &e>>  &7List all factions'
    - '&e&m--------------&r &2/f help 2 for more &e&m--------------'
  '2':
    - '&e&m------------------&r&c&l Page 2 &e&m--------------------'
    - '&3/f home     &e>>  &7Teleport to faction home'
    - '&3/f sethome &e>>  &7Set your faction home'
    - '&3/f leave    &e>>  &7Leave your faction'
    - '&3/f invite    &e>>  &7Invite a player to your faction'
    - '&3/f deinvite &e>>  &7Revoke invitation to player'
    - '&e&m--------------&r &2/f help 3 for more &e&m--------------'
  '3':
    - '&e&m------------------&r&c&l Page 3 &e&m--------------------'
    - '&3/f claim     &e>>  &7Claim land'
    - '&3/f unclaim  &e>>  &7Unclaim land'
    - '&3/f kick      &e>>  &7Kick player from your faction'
    - '&3/f mod      &e>>  &7Set player role in faction'
    - '&3/f chat     &e>>  &7Switch to faction chat'
    - '&e&m--------------&r &2/f help 4 for more &e&m--------------'
  '4':
    - '&e&m------------------&r&c&l Page 4 &e&m--------------------'
    - '&3/f version &e>>  &7Display version information'
    - '&e&m--------------&r&2 End of /f help &e&m-----------------'

############################################################
# +------------------------------------------------------+ #
# |                Configurable /f show                  | #
# +------------------------------------------------------+ #
############################################################

# You can use any variable here, including fancy messages. Color codes and or tags work fine.
# Lines that arent defined wont be sent (home not set, faction not peaceful / permanent, dtr freeze)
show:
  # First line can be {header} for default header, or any string (we recommend &m for smooth lines ;p)
  - '{header}'
  - '<a>Description: <i>{description}'
  - '<a>Joining: <i>{joining}    {peaceful}'
  - '<a>Land / Max: <i> {land} / {max-land}'
  - '<a>DTR: <i>{dtr} / {max-dtr} <a>Raidable: <i>{raidable}'
  - '<a>Faction Home: <i>{world}, {x}, {y}, {z}' # if no home is set, {z} = COMMAND_SHOW_NOHOME, from lang.yml
  - '<a>DTR Freeze: <i>{time-left}' # only shows if faction is frozen
  - '<a>Founded: <i>{create-date}'
  - '<a>This faction is permanent, remaining even with no members.' # only shows if faction is permanent
  - '<a>Land value: <i>{land-value} {land-refund}'
  - '<a>Balance: <i>{faction-balance}'
  - '<a>Allies(<i>{allies-count}<a>/<i>{max-allies}<a>): {allies} '
  - '<a>Online: (<i>{online-count}<a>/<i>{faction-size}<a>): {online}'
  - '<a>Offline: (<i>{offline-count}<a>/<i>{faction-size}<a>): {offline}'

############################################################
# +------------------------------------------------------+ #
# |                Configurable /f list                  | #
# +------------------------------------------------------+ #
############################################################

list:
  # You can only use {pagenumber} and {pagecount} in the header
  header: 'Faction List {pagenumber}/{pagecount}'
  # You can use any variables here
  factionless: '<i>Factionless<i> {factionless} online'
  # You can use any variable here
  entry: '<a>{faction} <i>{online-count} / {faction-size} online, <a>Land: <i>{land} / {max-land}, <a>Raidable: {raidable}'

############################################################
# +------------------------------------------------------+ #
# |                Big List of variables                 | #
# +------------------------------------------------------+ #
############################################################
# Fancy variables. Can only be used in /f show
#  - {allies}  : Lists each faction ally with tooltips
#  - {enemies} : Lists each faction enemy with tooltips
#  - {online}  : Lists all online members with tooltips
#  - {offline} : Lists all offline members with tooltips
# Player variables. Can be used in tooltips.show, scoreboards, or /f show
#  - {group}  : Players group
#  - {name}   : Players name
#  - {last-seen}  : Last time player was seen (if offline), or just 'Online'
#  - {player-balance} : Players balance
# Faction variables. Can be used in tooltips.list, scoreboards, or /f show
#  - {header}   : Default factions header (ex. /f show)
#  - {faction}  : Factions tag (if none, uses lang.yml for factionless name)
#  - {joining}  : How to join this faction
#  - {raidable} : True or false, if the faction is raidable
#  - {dtr}      : Factions deaths until raidable value
#  - {max-dtr}  : Factions max deaths until raidable value
#  - {land}     : # of claims faction has (in chunks)
#  - {max-land} : Max # of claims factio can make (in chunks)
#  - {warps}    : # of warps faction has
#  - {description} : Factions description
#  - {create-date} : Date faction was created
#  - {leader}      : Faction leader
#  - {land-value}    : Value of all claims
#  - {land-refund}   : Calculated refund value
#  - {allies-count}  : # of allies faction has
#  - {enemies-count} : # of enemies faction has
#  - {online-count}  : # of faction members online
#  - {offline-count} : # of faction members offline
#  - {faction-size}  : # of faction members (includes offline)
#  - {faction-balance}      : Faction bank balance
#  - {world}, {x}, {y}, {z} : Faction home variables. You don't need to use them all.
# General variables. Can be used anywhere.
# - {total-online}  : Total # of players on the server
# - {max-warps}     : Max # of warps a faction can set
# - {max-allies}    : Max # of allies a faction can have
# - {max-enemies}   : Max # of enemies a faction can have
# - {factionless}   : Count of all factionless players online
